#
# EGamma data
#

egamma:
- name: egamma_2018A
  das:
    key: /EGamma/swieland-KITv3_CustomNanoV9_Data_2018A-8572fdae940d4a6b8cd6e01ebd9b6132/USER
    instance: prod/phys03
  is_data: True

- name: egamma_2018B
  das:
    key: /EGamma/swieland-KITv3_CustomNanoV9_Data_2018B-8572fdae940d4a6b8cd6e01ebd9b6132/USER
    instance: prod/phys03
  is_data: True

- name: egamma_2018C
  das:
    key: /EGamma/swieland-KITv3_CustomNanoV9_Data_2018C-8572fdae940d4a6b8cd6e01ebd9b6132/USER
    instance: prod/phys03
  is_data: True

- name: egamma_2018D
  das:
    key: /EGamma/swieland-KITv3_CustomNanoV9_Data_2018D-8572fdae940d4a6b8cd6e01ebd9b6132/USER
    instance: prod/phys03
  is_data: True

#
# MET data
#

- name: met_2018A
  das:
    key: /MET/swieland-KITv3_CustomNanoV9_Data_2018A-8572fdae940d4a6b8cd6e01ebd9b6132/USER
    instance: prod/phys03
  is_data: True

- name: met_2018B
  das:
    key: /MET/swieland-KITv3_CustomNanoV9_Data_2018B-8572fdae940d4a6b8cd6e01ebd9b6132/USER
    instance: prod/phys03
  is_data: True

- name: met_2018C
  das:
    key: /MET/swieland-KITv3_CustomNanoV9_Data_2018C-8572fdae940d4a6b8cd6e01ebd9b6132/USER
    instance: prod/phys03
  is_data: True

- name: met_2018D
  das:
    key: /MET/swieland-KITv3_CustomNanoV9_Data_2018D-8572fdae940d4a6b8cd6e01ebd9b6132/USER
    instance: prod/phys03
  is_data: True

#
# JetHT data
#

- name: jetht_2018A
  das:
    key: /JetHT/swieland-KITv3_CustomNanoV9_Data_2018A-8572fdae940d4a6b8cd6e01ebd9b6132/USER
    instance: prod/phys03
  is_data: True

- name: jetht_2018B
  das:
    key: /JetHT/swieland-KITv3_CustomNanoV9_Data_2018B-8572fdae940d4a6b8cd6e01ebd9b6132/USER
    instance: prod/phys03
  is_data: True

- name: jetht_2018C
  das:
    key: /JetHT/swieland-KITv3_CustomNanoV9_Data_2018C-8572fdae940d4a6b8cd6e01ebd9b6132/USER
    instance: prod/phys03
  is_data: True

- name: jetht_2018D
  das:
    key: /JetHT/swieland-KITv3_CustomNanoV9_Data_2018D-8572fdae940d4a6b8cd6e01ebd9b6132/USER
    instance: prod/phys03
  is_data: True
